# Generated by Django 4.1.5 on 2023-03-26 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_faq'),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('photo', models.ImageField(upload_to='category/')),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('mrp', models.FloatField()),
                ('sellingprice', models.FloatField()),
                ('material', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('photo', models.ImageField(upload_to='product/')),
                ('deliveryby', models.DateField()),
                ('size', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('style', models.CharField(max_length=100)),
                ('tag', models.CharField(choices=[('best', 'best'), ('featured', 'featured'), ('latest', 'latest'), ('new', 'new')], max_length=50)),
                ('categoryid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.category')),
            ],
            options={
                'db_table': 'product',
            },
        ),
    ]
