# Generated by Django 4.1.5 on 2023-03-28 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_remove_product_deliveryby_remove_product_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='photo1',
            field=models.ImageField(default='', upload_to='product/'),
        ),
        migrations.AddField(
            model_name='product',
            name='photo2',
            field=models.ImageField(default='', upload_to='product/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(default='', upload_to='product/'),
        ),
    ]
