# Generated by Django 4.1.5 on 2023-03-30 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_product_photo1_product_photo2_alter_product_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='mrp',
        ),
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.FloatField(blank='true', default='1.1', null='true'),
            preserve_default='true',
        ),
    ]
