# Generated by Django 4.1.5 on 2023-04-28 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_gallery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='name',
        ),
    ]
