# Generated by Django 4.1.5 on 2023-05-19 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_city_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='phone',
        ),
    ]
