# Generated by Django 4.1.5 on 2023-05-23 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_remove_review_phone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='city',
        ),
    ]
