# Generated by Django 4.1.5 on 2023-04-26 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='phone_no',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(choices=[('Amritsar', 'Amritsar'), ('Bathinda', 'Bathinda'), ('Bhucho Mandi', 'Bhucho Mandi'), ('Talwandi Sabo', 'Talwandi Sabo'), ('Rampura', 'Rampura'), ('Maur Mandi', 'Maur Mandi'), ('Faridkot', 'Faridkot'), ('Moga', 'Moga'), ('Dabawali', 'Dabawali'), ('Jaito', 'Jaito'), ('Sunam', 'Sunam'), ('Sangrur', 'Sangrur'), ('Patiala', 'Patiala'), ('Kotakpura', 'Kotakpura'), ('Malout', 'Malout'), ('Ludhiana', 'Ludhiana'), ('Jalandhar', 'Jalandhar'), ('Barnala', 'Barnala'), ('Bajakhana', 'Bajakhana'), ('Kaliawali', 'Kaliawali'), ('Malerkotla', 'Malerkotla'), ('Khanna', 'Khanna'), ('Muktsar', 'Muktsar'), ('Rajpura', 'Rajpura')], max_length=100),
        ),
    ]
