# Generated by Django 4.1.5 on 2023-04-28 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(choices=[('Amritsar', 'Amritsar'), ('Bathinda', 'Bathinda'), ('Bhucho Mandi', 'Bhucho Mandi'), ('Barnala', 'Barnala'), ('Bajakhana', 'Bajakhana'), ('Dabawali', 'Dabawali'), ('Faridkot', 'Faridkot'), ('Jalandhar', 'Jalandhar'), ('Jaito', 'Jaito'), ('Khanna', 'Khanna'), ('Kaliawali', 'Kaliawali'), ('Kotakpura', 'Kotakpura'), ('Ludhiana', 'Ludhiana'), ('Maur Mandi', 'Maur Mandi'), ('Malout', 'Malout'), ('Malerkotla', 'Malerkotla'), ('Moga', 'Moga'), ('Muktsar', 'Muktsar'), ('Patiala', 'Patiala'), ('Rampura', 'Rampura'), ('Rajpura', 'Rajpura'), ('Sunam', 'Sunam'), ('Sangrur', 'Sangrur'), ('Talwandi Sabo', 'Talwandi Sabo')], max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='postal_code',
            field=models.CharField(choices=[('143001', '143001'), ('151001', '151001'), ('151101', '151101'), ('148103', '148103'), ('151205', '151205'), ('125104', '125104'), ('151213', '151213'), ('144001', '144001'), ('151202', '151202'), ('141401', '141401'), ('125201', '125201'), ('151204', '151204'), ('141001', '141001'), ('151509', '151509'), ('152107', '152107'), ('148023', '148023'), ('142001', '142001'), ('152026', '152026'), ('147001', '147001'), ('151103', '151103'), ('140401', '140401'), ('148028', '148028'), ('148001', '148001'), ('151302', '151302')], max_length=30),
        ),
    ]
