# Generated by Django 4.1.5 on 2023-05-02 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_ordernow_remove_order_phone_no_alter_order_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='phn_no',
            field=models.CharField(default='', max_length=20),
        ),
    ]
