# Generated by Django 4.1.5 on 2023-05-08 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_order_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='phn_no',
            new_name='phone_number',
        ),
    ]
