# Generated by Django 4.1.5 on 2023-05-12 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_order_userid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='userid',
        ),
    ]
