# Generated by Django 4.1.5 on 2023-05-12 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_order_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_date',
            field=models.CharField(default='', max_length=10),
        ),
    ]
