# Generated by Django 4.1.5 on 2023-05-23 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_remove_order_postal_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(choices=[('Amritsar', 'Amritsar'), ('Bathinda', 'Bathinda'), ('Barnala', 'Barnala'), ('Bajakhana', 'Bajakhana'), ('Bhucho Mandi', 'Bhucho Mandi'), ('Dabawali', 'Dabawali'), ('Faridkot', 'Faridkot'), ('Goniana', 'Goniana'), ('Jaito', 'Jaito'), ('Jalandhar', 'Jalandhar'), ('Khanna', 'Khanna'), ('Kaliawali', 'Kaliawali'), ('Kotakpura', 'Kotakpura'), ('Ludhiana', 'Ludhiana'), ('Malout', 'Malout'), ('Maur Mandi', 'Maur Mandi'), ('Malerkotla', 'Malerkotla'), ('Moga', 'Moga'), ('Muktsar', 'Muktsar'), ('Patiala', 'Patiala'), ('Rajpura', 'Rajpura'), ('Rampura', 'Rampura'), ('Sunam', 'Sunam'), ('Sangrur', 'Sangrur'), ('Talwandi Sabo', 'Talwandi Sabo')], max_length=100),
        ),
    ]
